# Generated by Django 4.0.1 on 2022-02-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='creation_date',
        ),
    ]
