# Generated by Django 4.0.1 on 2022-02-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_todolistitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
