# Generated by Django 4.0.1 on 2022-02-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_todolistitem_associated_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='list_ref',
        ),
    ]
